#!/usr/bin/env bash

# Install cloudflared
# https://pkg.cloudflare.com/

set -euo pipefail

echo "Installing cloudflared..."

# Add Cloudflare GPG key
echo "Adding Cloudflare GPG key..."
sudo mkdir -p --mode=0755 /usr/share/keyrings
curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

# Add this repo to your apt repositories
echo "Adding Cloudflare repository..."
echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list

# install cloudflared
echo "Installing cloudflared package..."
sudo apt-get update && sudo apt-get install -y cloudflared

echo "cloudflared installation completed!"
cloudflared --version
