#!/usr/bin/env bash

export APPLIED_BASHALIAS=1

# cd to git repository root
alias cdd='cd $(git rev-parse --show-toplevel 2>/dev/null || echo ".")'

alias c='claude'
alias cc='claude --continue'
alias cr='claude --resume'

alias zz='zed'
alias co="code"

alias m="mise"
alias me="mise run encrypt"

alias u="uv"
alias ur="uv run"

alias tf="terraform"

alias ll='lt'
alias lll='lt --level=3'
alias la='ls -a'

alias cm="chezmoi"
alias cme='chezmoi edit --apply'
alias cma='chezmoi add'
alias cmae='chezmoi add --encrypt'
alias cmm='chezmoi merge'

alias z='zellij'
alias za='zellij attach'

alias lg='lazygit'
alias gg='git-graph'

alias ts='tailscale'

alias ai='sudo apt update && sudo apt install'
alias au='sudo apt update && sudo apt upgrade'

# try until last command succeeds
alias trytilsucess='while [ $? -ne 0 ]; do eval $(history -p !!); done'
