#!/usr/bin/env bash

export APPLIED_BASHALIAS=1

# cd to git repository root
alias cdd='cd $(git rev-parse --show-toplevel 2>/dev/null || echo ".")'

alias c='claude --allow-dangerously-skip-permissions'
alias cc='c --continue'
alias ccf='c --continue --fork-session'
alias cr='c --resume'
alias crf='c --resume --fork-session'
alias cdo='sudo $(which claude)'

alias zz='zed'
alias co="code"

alias m="mise"

alias u="uv"
alias ur="uv run"

alias tf="terraform"

alias ll='lt'
alias lll='lt --level=3'
alias la='ls -a'

alias cm="chezmoi"
alias cme='chezmoi edit --apply'
alias cma='chezmoi add'
alias cmae='chezmoi add --encrypt'
alias cmm='chezmoi merge'

alias zj='zellij'
alias zja='zellij attach'

alias lg='lazygit'
alias gg='git-graph'

alias ts='tailscale'

alias ai='sudo apt update && sudo apt install'
alias au='sudo apt update && sudo apt upgrade'

# try until last command succeeds
alias trytilsuccess='while [ $? -ne 0 ]; do eval $(history -p !!); done'
