[tools]
node = "lts"
just = "latest"
rust = "latest"
"cargo:xcp" = "latest"
java = "latest"
bun = "latest"
"pipx:trash-cli" = "latest"
"cargo:mprocs" = "latest"
gcloud = "latest"
"npm:wsl-open" = "latest"
go = "latest"
python = "3.12"
poetry = "latest"
mc = "latest"
sops = "latest"
age = "latest"
"cargo:rops-cli" = "latest"
pkl = "latest"
hk = "latest"
uv = "latest"
bat = "latest"
"pipx:ttok" = "latest"
watchexec = "latest"
chezmoi = "latest"
"ubi:cantino/mcfly" = "latest"
usage = "latest"
"ubi:git-town/git-town" = "latest"
"cargo:exa" = "latest"
"cargo:bat" = "latest"
"npm:@postgrestools/postgrestools" = "latest"
zellij = "latest"
lazygit = "latest"

[settings]
experimental = true

[settings.python]
compile = true

[settings.pipx]
uvx = true

[settings.npm]
bun = true
