["./dorothy"]
type = "git-repo"
url = "https://github.com/bevry/dorothy.git"
refreshPeriod = "168h"

["./pg-essentials"]
type = "git-repo"
url = "https://github.com/bnnanet/pg-essentials.git"
refreshPeriod = "168h"

["./keyboards/layouts/graphite/graphite-layout"]
type = "git-repo"
url = "https://github.com/ninyawee/graphite-layout.git"
refreshPeriod = "168h"

["./plover-5.0.0rc1-x86_64.AppImage"]
type = "file"
url = "https://github.com/openstenoproject/plover/releases/download/v5.0.0rc1/plover-5.0.0rc1-x86_64.AppImage"
executable = true

["./ventoy-1.1.07-linux"]
type = "archive"
url = "https://github.com/ventoy/Ventoy/releases/download/v1.1.07/ventoy-1.1.07-linux.tar.gz"
stripComponents = 2

["./keymapp"]
type = "archive"
url = "https://oryx.nyc3.cdn.digitaloceanspaces.com/keymapp/keymapp-latest.tar.gz"
